name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 4.3.0
homepage: https://github.com/builttoroam/device_calendar/tree/master

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  sprintf: ^7.0.0
  timezone: ^0.9.0
  # flutter_native_timezone: ^2.0.0
  flutter_native_timezone:
    git:
      url: https://github.com/nguyenlamzx/flutter_native_timezone.git
      ref: 960d3b8d1e98dcc9f938e51fe9e32b755af38f4b

# dependency_overrides:
#   flutter_native_timezone:
#     git:
#       url: https://github.com/nguyenlamzx/flutter_native_timezone.git
#       ref: 960d3b8d1e98dcc9f938e51fe9e32b755af38f4b

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.devicecalendar
        pluginClass: DeviceCalendarPlugin
      ios:
        pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"
